apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "taiga.fullname" . }}-async
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    app.kubernetes.io/component: taigaAsync
spec:
  serviceName: {{ template "taiga.fullname" . }}-async
  replicas: 1
  selector:
    matchLabels:
      {{- include "taiga.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: taiga-async
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "taiga.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: taiga-async
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.taigaAsync.podSecurityContext | nindent 8 }}
      containers:
        - name: taiga-async
          securityContext:
            {{- toYaml .Values.taigaAsync.securityContext | nindent 12 }}
          image: "{{ .Values.taigaAsync.image.repository }}:{{ .Values.taigaAsync.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.taigaAsync.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000  
          command:
            - /taiga-back/docker/async_entrypoint.sh
          env:
            - name: ENABLE_TELEMETRY
              value: {{ lower .Values.env.enableTelemetry | quote }}

            - name: POSTGRES_HOST
              value: "{{template "taiga.fullname" . }}-db"
            - name: POSTGRES_DB
              value: {{ .Values.env.postgresDB | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.env.postgresPassword | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.env.postgresUser | quote }}

            - name: RABBITMQ_PASS
              value: {{ .Values.env.rabbitmqPass | quote }}
            - name: RABBITMQ_USER
              value: {{ .Values.env.rabbitmqUser | quote }}
            - name: CELERY_BROKER_URL
              value: "amqp://taiga:taiga@{{template "taiga.fullname" . }}-async-rabbitmq:{{  .Values.taigaAsyncRabbitmq.service.port }}/taiga"

            - name: TAIGA_SECRET_KEY
              value: {{ .Values.env.taigaSecretKey | quote }}
            - name: TAIGA_SITES_DOMAIN
              value: {{ .Values.env.taigaSitesDomain | quote }}
            - name: TAIGA_SITES_SCHEME
              value: {{ .Values.env.taigaSitesScheme | quote }}
          volumeMounts:
            - mountPath: /taiga-back/static
              name: taiga-static-data
            - mountPath: /taiga-back/media
              name: taiga-media-data
          {{- with .Values.taigaAsync.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.taigaAsync.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.taigaAsync.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.taigaAsync.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: taiga-static-data
          persistentVolumeClaim:
            claimName: {{ include "taiga.fullname" . }}-static-data
        - name: taiga-media-data
          persistentVolumeClaim:
            claimName: {{ include "taiga.fullname" . }}-media-data
